trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndDeploy
  displayName: Build and Deploy Stage
  jobs:
  - job: MavenPackageAndDeployJar
    displayName: Build and Deploy job¯

    steps:
    - task: Maven@3
      displayName: 'maven build'
      inputs:
        mavenPomFile: 'pom.xml' 
        goals: 'package'
    - task: CopyFilesOverSSH@0
      displayName: copy jar to tomcat
      inputs:
        sshEndpoint: 'dev-server-connection'
        SourceFolder: '$(System.DefaultWorkingDirectory)/target/'
        Contents: '*.war'
        TargetFolder: '/var/lib/tomcat9/webapps/'
        OverWrite: true
