trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaVersion@1
  inputs:
    version: '8'

- script: |
    ./mvnw package --file pom.xml
  displayName: 'Maven package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './target/*.jar'
    ArtifactName: 'blog_app'
