
- name: Setup Tomcat9 & Deploy Artifact
  hosts: appserver_grp
  become: yes
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"
  tasks:
    - name: Download latest FirstProject.war from nexus
      get_url:
        url: "http://{{USER}}:{{PASS}}@{{nexusip}}:8081/repository/{{reponame}}/{{groupid}}/{{artifactid}}/{{build_no}}-{{time}}/{{star_blog_version}}"
        dest: "/tmp/star_blog-{{star_blog_version}}"
      register: wardeploy
      tags:
        - deploy

    - stat:
        path: /usr/local/tomcat9/webapps/ROOT
      register: artifact_stat
      tags:
        - deploy

    - name: Stop tomcat svc
      service:
        name: tomcat
        state: stopped
      tags:
        - deploy

    - name: Try Backup and Deploy
      block:
        - name: Archive ROOT dir with timestamp
          archive:
            path: /usr/local/tomcat9/webapps/ROOT
            dest: "/opt/ROOT_{{timestamp}}.tgz"
          when: artifact_stat.stat.exists
          register: archive_info
          tags:
            - deploy

        - name: Delete current artifact
          file:
            path: "{{item}}"
            state: absent
          when: archive_info.changed
          loop:
            - /usr/local/tomcat9/webapps/ROOT.war
          tags:
            - deploy

        - name: Try deploy artifact else restore from previos old_ROOT
          copy:
            src: "/tmp/star_blog-{{star_blog_version}}"
            dest: /usr/local/tomcat9/webapps/ROOT.war
            remote_src: yes
          register: deploy_info
          tags:
            - deploy

      rescue:
        - name: Start tomcat svc
          service:
            name: tomcat
            state: started

    - name: Start tomcat svc
      service:
        name: tomcat
        state: started

    - name: Wait until ROOT.war is extracted to ROOT directory
      wait_for:
        path: /usr/local/tomcat9/webapps/ROOT
      tags:
        - deploy