
- name: Setup Tomcat9 & Deploy Artifact
  hosts: appserver_grp
  become: yes
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"
  tasks:
    - name: Download latest FirstProject.war from nexus
      get_url:
        url: "http://{{USER}}:{{PASS}}@{{nexusip}}:8081/repository/{{reponame}}/{{groupid}}/{{artifactid}}/{{build_no}}-{{time}}/{{star_blog_version}}"
        dest: "/tmp/star_blog-{{star_blog_version}}"
      register: wardeploy
      tags:
        - deploy

    - stat:
        path: /usr/local/tomcat9/webapps/ROOT
      register: artifact_stat
      tags:
        - deploy

    - name: Stop tomcat svc
      service:
        name: tomcat
        state: stopped
      tags:
        - deploy

    - name: Try Backup and Deploy
      block:
        - name: Archive ROOT dir with timestamp
          archive:
            path: /usr/local/tomcat9/webapps/ROOT
            dest: "/opt/ROOT_{{timestamp}}.tgz"
          when: artifact_stat.stat.exists
          register: archive_info
          tags:
            - deploy

        - name: copy ROOT dir with old_ROOT name
          shell: cp -r ROOT old_ROOT
          args:
            chdir: /usr/local/tomcat9/webapps/

        - name: Delete current artifact
          file:
            path: "{{item}}"
            state: absent
          when: archive_info.changed
          loop:
            - /usr/local/tomcat9/webapps/ROOT/
            - /usr/local/tomcat9/webapps/ROOT.war
          tags:
            - deploy

        - name: Try deploy artifact else restore from previos old_ROOT
          block:
            - name: Deploy star-blog artifact
              copy:
                src: "/tmp/star_blog-{{star_blog_version}}"
                dest: /usr/local/tomcat9/webapps/ROOT.war
                remote_src: yes
              register: deploy_info
              tags:
                - deploy
            - name: Extract ROOT.war into ROOT
              unarchive:
                src: /usr/local/tomcat9/webapps/ROOT.war
                dest: /usr/local/tomcat9/webapps
                remote_src: yes
          rescue:
            - shell: cp -r old_ROOT ROOT
              args:
                chdir: /usr/local/tomcat9/webapps/

      rescue:
        - name: Start tomcat svc
          service:
            name: tomcat
            state: started

    - name: Start tomcat svc
      service:
        name: tomcat
        state: started
      when: deploy_info.changed
      tags:
        - deploy