
- name: Setup Tomcat9 & Deploy Artifact
  hosts: appserver_grp
  become: yes
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"
  tasks:
    - name: Download latest FirstProject.war from nexus
      get_url:
        url: "http://{{USER}}:{{PASS}}@{{nexusip}}:8081/repository/{{reponame}}/{{groupid}}/{{artifactid}}/{{build_no}}-{{time}}/{{star_blog_version}}"
        dest: "/tmp/star_blog-{{star_blog_version}}"
      register: wardeploy
      tags:
        - deploy

    - name: Stop tomcat svc
      service:
        name: tomcat
        state: stopped

    - name: Deploy star-blog artifact
      copy:
        src: "/tmp/star_blog-{{star_blog_version}}"
        dest: /usr/local/tomcat9/webapps/ROOT.war
        remote_src: yes

    - name: Start tomcat svc
      service:
        name: tomcat
        state: started